// AutolinkedNativeModules.g.cs contents generated by "react-native autolink-windows"

using System.Collections.Generic;

// Namespaces from react-native-module-device
using ReactNativeModuleDevice;

// Namespaces from react-native-module-image
using ReactNativeModuleImage;

// Namespaces from react-native-module-printer
using ReactNativeModulePrinter;

// Namespaces from react-native-module-user
using ReactNativeModuleUser;

// Namespaces from react-native-screens
using RNScreens;

namespace Microsoft.ReactNative.Managed
{
    internal static class AutolinkedNativeModules
    {
        internal static void RegisterAutolinkedNativeModulePackages(IList<IReactPackageProvider> packageProviders)
        { 
            // IReactPackageProviders from react-native-module-device
            packageProviders.Add(new ReactNativeModuleDevice.ReactPackageProvider());
            // IReactPackageProviders from react-native-module-image
            packageProviders.Add(new ReactNativeModuleImage.ReactPackageProvider());
            // IReactPackageProviders from react-native-module-printer
            packageProviders.Add(new ReactNativeModulePrinter.ReactPackageProvider());
            // IReactPackageProviders from react-native-module-user
            packageProviders.Add(new ReactNativeModuleUser.ReactPackageProvider());
            // IReactPackageProviders from react-native-screens
            packageProviders.Add(new RNScreens.ReactPackageProvider());
        }
    }
}
